CREATE TABLE SWIFT_FORMAT
(
  MESG_TYPE    VARCHAR2(6 CHAR),
  IN_OUT       VARCHAR2(3 CHAR),
  FIELD        VARCHAR2(3 CHAR),
  DEST_FIELD   VARCHAR2(105 CHAR),
  RANGE_FROM   NUMBER,
  RANGE_COUNT  NUMBER,
  SEQUENCE     NUMBER
)