SET DEFINE OFF;
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '77B', 'INFORMATION1', 6, 
    0, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '77B', 'INFORMATION2', 1, 
    0, 2);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '77B', 'INFORMATION3', 1, 
    0, 3);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '77B', 'INFORMATION4', 1, 
    0, 4);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '77B', 'INFORMATION5', 1, 
    0, 5);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '50A', 'BY_ORDER_OF1', 7, 
    0, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '50A', 'BY_ORDER_OF2', 1, 
    0, 2);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '50A', 'BY_ORDER_OF3', 1, 
    0, 3);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '50A', 'BY_ORDER_OF4', 1, 
    0, 4);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '50A', 'BY_ORDER_OF5', 1, 
    0, 5);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '20', 'USER_REF_NO', 5, 
    0, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '23B', 'BANK_OPER_CODE', 6, 
    0, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '32A', 'DR_AMOUNT', 1, 
    0, 3);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '32A', 'VALUE_DATE', 6, 
    6, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '32A', 'DR_CCY', 1, 
    3, 2);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '50K', 'BY_ORDER_OF5', 1, 
    0, 5);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '70', 'PAYMENT_DETAILS2', 1, 
    0, 2);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '70', 'PAYMENT_DETAILS1', 5, 
    0, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '70', 'PAYMENT_DETAILS3', 1, 
    0, 3);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '50K', 'BY_ORDER_OF4', 1, 
    0, 4);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '50K', 'BY_ORDER_OF1', 7, 
    0, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '50K', 'BY_ORDER_OF2', 1, 
    0, 2);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '50K', 'BY_ORDER_OF3', 1, 
    0, 3);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '59', 'ULTIMATE_BEN5', 1, 
    0, 5);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '59', 'ULTIMATE_BEN4', 1, 
    0, 4);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '59', 'ULTIMATE_BEN1', 6, 
    0, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '59', 'ULTIMATE_BEN3', 1, 
    0, 3);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '59', 'ULTIMATE_BEN2', 1, 
    0, 2);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '70', 'PAYMENT_DETAILS4', 1, 
    0, 4);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '72', 'INFORMATION1', 5, 
    0, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '71A', 'UNUSEFUL', 6, 
    0, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '72', 'INFORMATION2', 1, 
    0, 2);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '72', 'INFORMATION3', 1, 
    0, 3);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '72', 'INFORMATION4', 1, 
    0, 4);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '72', 'INFORMATION5', 1, 
    0, 5);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '{1F', 'SENDER', 103, 
    8, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '50F', 'BY_ORDER_OF1', 7, 
    0, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '50F', 'BY_ORDER_OF2', 1, 
    0, 2);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '50F', 'BY_ORDER_OF3', 1, 
    0, 3);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '50F', 'BY_ORDER_OF4', 1, 
    0, 4);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '50F', 'BY_ORDER_OF5', 1, 
    0, 5);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '21', 'USER_REF_NO', 5, 
    0, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '32B', 'DR_AMOUNT', 1, 
    0, 2);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '32B', 'DR_CCY', 6, 
    3, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '26T', 'KOD_26', 6, 
    0, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '52A', 'UNUSEFUL', 6, 
    0, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '53A', 'SENDER53', 6, 
    8, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '54A', 'SENDER54', 6, 
    8, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '57A', 'UNUSEFUL', 6, 
    0, 1);
Insert into SWIFT_FORMAT
   (MESG_TYPE, IN_OUT, FIELD, DEST_FIELD, RANGE_FROM, 
    RANGE_COUNT, SEQUENCE)
 Values
   ('103', 'I', '52D', 'UNUSEFUL', 6, 
    0, 1);
COMMIT;
